import Config

# Configure your database
config :rule_maven, RuleMaven.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "rule_maven_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  types: RuleMaven.PostgresTypes

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :rule_maven, RuleMavenWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # DEV_PORT lets a worktree run its own dev server beside the main
  # checkout's (default 4000), same idea as the per-worktree test port.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("DEV_PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "7D7c6/MoalDOGvmWDRAavfuaRvU4fnOcsRW1XgxmnLfVjzzsEl5uRmW9Z0KAV7qI",
  watchers: []

# Host used to build links in outbound email (password reset, confirmation).
# Independent of the Endpoint's own host/port above.
config :rule_maven, :public_url, "http://localhost:#{System.get_env("DEV_PORT") || "4000"}"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
#
# The file watcher reports ABSOLUTE paths, so each pattern is unanchored on
# the left — which also made them match the same layout inside git worktrees
# under .claude/worktrees/<name>/, blasting reload storms at every open tab
# whenever a worktree was created, edited, or removed. The lookahead guard
# rejects any path inside .claude/.
not_in_worktree = "\\A(?!.*/\\.claude/)"

config :rule_maven, RuleMavenWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      Regex.compile!(
        not_in_worktree <> ~S".*priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"
      ),
      # Gettext translations
      Regex.compile!(not_in_worktree <> ~S".*priv/gettext/.*\.po$"),
      # Router, Controllers, LiveViews and LiveComponents
      Regex.compile!(not_in_worktree <> ~S".*lib/rule_maven_web/router\.ex$"),
      Regex.compile!(
        not_in_worktree <> ~S".*lib/rule_maven_web/(controllers|live|components)/.*\.(ex|heex)$"
      )
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :rule_maven, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# LLM and BGG configured via Settings page (stored in DB).
